// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs90RbRAFgo4QAdqta_hrRuhOSlEfF-nk',
    appId: '1:767846292948:android:50f729736292ee46554a41',
    messagingSenderId: '767846292948',
    projectId: 'nothing-v2zdm3',
    databaseURL: 'https://nothing-v2zdm3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nothing-v2zdm3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0TSdUrLZf1QHK3YZ5S0lk4e_eWGEo_Y',
    appId: '1:767846292948:ios:73ffebc54759fd7d554a41',
    messagingSenderId: '767846292948',
    projectId: 'nothing-v2zdm3',
    databaseURL: 'https://nothing-v2zdm3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nothing-v2zdm3.appspot.com',
    iosClientId: '767846292948-1j73pccuac9dv4vqona47pdid0nc63f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.majmu',
  );

}